version: "3.8"
services:
  api:
    build: .
    command: bash -c "pytest -vv"
    volumes:
      - .:/backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
    networks:
      - entrees-internal

  db:
    image: postgis/postgis:14-master
    volumes:
      - pg-data-entrees:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - entrees-internal

volumes:
  pg-data-entrees:
networks:
  entrees-internal:
